# Generated by Django 5.1.3 on 2024-11-22 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="benifits",
            new_name="benefits",
        ),
    ]
